### ISSUE TITLE
Add a formatter for labels requiring a degree symbol

### ISSUE THREAD

**Issue by dpseidel** [r-lib/scales#159]
Add a formatter that adds degree symbols and characters to a numeric vector to make labels for things like temperature or latitude and longitude (as currently done by geom_sf). 

The current way to get this to format correctly in ggplot is something like:

```
library(ggplot2)
ggplot(data.frame(), aes(1, 1)) + scale_x_continuous(labels = c(
  expr(160 * degree * W), expr(140 * degree * W),
  expr(120 * degree * W), expr(100 * degree * W), 
  expr(0 * degree * W))
```

**Comment by mikmart** [comment]
Could this be done with the Unicode symbol `"\u00b0"` (`°`) rather than with plotmath expressions?

``` r

library(ggplot2)
ggplot(NULL, aes(letters[1:2], letters[1:2])) +
  scale_x_discrete(labels = expression(100 * degree * W, 120 * degree * W)) +
  scale_y_discrete(labels = paste0(c(60, 70), "\u00b0N"))
```

![](https://i.imgur.com/TRLumJC.png)

The printed symbol is not identical (Unicode is a bit smaller) but it would certainly result in a more general purpose formatter. An implementation would also be super simple, basically just be a wrapper for `number()` that prefixes the given suffix with `"\u00b0"`.

Created on 2018-09-06 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0.9000).
