### ISSUE TITLE
v1.0 issue with comma rounding small numbers 0.

### ISSUE THREAD

**Issue by sada1993** [r-lib/scales#201]
In version 0.5.0 the following code works perfectly fine. In Version 1.0.0 however `comma` results in smaller numbers being rounded to 0 ( the y-axis is all zeros). I could exclude comma but my range of y-values are large hence the larger numbers need to be comma separated.

```
library(dplyr)
library(ggplot2)
library(scales)

data.frame(x =seq(0,100,1), y = seq(0,0.01,0.0001))%>%
  ggplot(aes(x,y))+
  geom_line()+
  scale_y_continuous(labels = comma)
```

**Comment by dpseidel** [comment]
This has to do with a change in arguments and defaults with number formatters in version 1.0 
Simply use `comma_format` and specify a different accuracy if you want breaks with more decimal places: 

``` r
library(dplyr)
library(ggplot2)
library(scales)

data.frame(x =seq(0,100,1), y = seq(0,0.01,0.0001))%>%
  ggplot(aes(x,y))+
  geom_line()+
  scale_y_continuous(labels = comma_format(accuracy = .001))
```

![](https://i.imgur.com/NHNyX7F.png)

<sup>Created on 2019-02-25 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

Given your description and reprex I believe this is expected behavior and will close this issue now. Does this solve your issue? If not, please respond with more information identifying the problem.
