### ISSUE TITLE
[Question] Is scales::pvalue() guaranteed to be kept?

### ISSUE THREAD

**Issue by Generalized** [r-lib/scales#377]
This function is extremely useful in clinical reporting, where used alone with the result to format.
I read it is "superseded" now. It would be truly a pity to lose it in future, making one to either write (another) custom function or use other packages. Sure, it's not a complicated piece of code and one can easily write one themselves, but having it "onboard" makes the environment cleaner. 
It's said that _"These functions are kept for backward compatibility; you should switch to [label_pvalue()](http://127.0.0.1:44009/help/library/scales/help/label_pvalue) for new code."_. Does "kept" here mean in "this and a maybe few more versions" or forever?

**Comment by thomasp85** [comment]
In general "Deprecated" means that over the cause of a number of releases it will be removed. Superseded means that we have no plans of removing it but we are not advocating its use since we have found what we think is a better approach.

So, while there are no guarantees in life, we have no plans to remove `scales::pvalue()` in the future
