### ISSUE TITLE
date_format does not work correctly on hms objects

### ISSUE THREAD

**Issue by trittweiler** [r-lib/scales#88]
```
> library(hms)
> library(scales)
> t <- as.hms(Sys.time())
> date_format("%H:%M", tz="GMT")(t)
[1] "12:30:20.18367"
> format(t, "%H:%M", tz="GMT")
[1] "12:30:20.18367"
> strftime(t, "%H:%M", tz="GMT")
[1] "12:30"
```

As the function is called "date_format" behaving like "format" is perhaps the right behaviour.

Is this perhaps rather an issue with the hms library which should implement some kind of format method?

**Comment by karawoo** [comment]
If I understand correctly the issue here is that `date_format` behaves differently for POSIXct and hms objects, and for hms objects it shows seconds even when the format requested is only `"%H:%M"`. A more illustrative example is below:

``` r
library(hms)
library(scales)

t <- Sys.time()

date_format("%H:%M", tz = "GMT")(t)
#> [1] "17:22"
date_format("%H:%M", tz = "GMT")(as.hms(t))
#> [1] "17:22:08.155499"

format(t, "%H:%M", tz = "GMT")
#> [1] "17:22"
format(as.hms(t), "%H:%M", tz = "GMT")
#> [1] "17:22:08.155499"
```

`date_format` uses `format` under the hood, so that is why they behave the same. @hadley do you think this behavior should change? Or is this issue more appropriate for the `hms` package?

**Comment by hadley** [comment]
I'd rewrite `date_format()` along these lines:

```R
date_format <- function(format = "%Y-%m-%d", tz = 'UTC') {
  function(x) {
    if (inherits(x, "POSIXt")) {
      format(x, format, tz = tz)  
    } else if (inherits(x, "Date")) {
      
    } else if (inherits(x, "difftime")) {
      
    } else {
      stop("Unsupported type (needs better error message)")
    }
      
  }
}
```

Alternatively, it might be better to add a custom time format type — it's a bit odd to use `date_format()` with a time.
